version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobboard-backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - NODE_ENV=development
      - PG_USER=postgres
      - PG_HOST=centerbeam.proxy.rlwy.net
      - PG_DATABASE=railway
      - PG_PASSWORD=qOcewAJqFmGyICfPxcayjBftgytWVJan
      - PG_PORT=46774
      - MONGO_URI=mongodb+srv://upadhayayyogesh832:123freelanceproject123@cluster0.ga6zbb8.mongodb.net/TTTAsingment?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=supersecretjwtkey_replace_in_production
      - CLOUDINARY_CLOUD_NAME=dil5x4cxh
      - CLOUDINARY_API_KEY=585782464739395
      - CLOUDINARY_API_SECRET=e8q7eMypVZX30vTbT_m7PI4iUHc
    networks:
      - jobboard-network

networks:
  jobboard-network:
    driver: bridge
